cc_licenses/templates/includes/about_cc.html, cc_licenses/templates/includes/about_cc_and_license.html, cc_licenses/templates/includes/disclaimer.html, cc_licenses/templates/includes/red_alert.html, cc_licenses/templates/includes/use_of_licenses.html
Fixes #[issue number] by @[issue author]
https://caktus.atlassian.net/browse/CC-27
- `has-background-info-light` has been added to info divs. `style` tags has been removed.
- `exclamation-circle` icon has been added to `red-alert` div. `info` icon has been removed.
<details>
```
Version 1.1
Suite D4700 …
```
=> [CC-27] Use Vocabulary Updates Where We Can

requirements/dev.txt
This PR imports the release version of cc-link-checker instead of cc-link-checker's master branch.
=> Target cc-link-checker release instead of master branch.

cc_licenses/settings/base.py, i18n/tests/test_utils.py, i18n/utils.py, licenses/git_utils.py, licenses/management/commands/check_for_translation_updates.py, licenses/management/commands/load_html_files.py, licenses/management/commands/publish.py, licenses/tests/test_git_utils.py, licenses/tests/test_transifex.py, licenses/tests/test_utils.py, licenses/transifex.py, licenses/utils.py
Create git branch when transifex updated, add changed translation files, commit, and push upstream.
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> [CC-31] Create branch when transifex updated

i18n/utils.py, licenses/management/commands/load_html_files.py, licenses/management/commands/upload_license_messages.py, licenses/models.py, licenses/tests/test_models.py, licenses/tests/test_transifex.py, licenses/transifex.py
Running compilemessages from load_html_files fails, just save mofile ourselves.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> [CC-31] Running compilemessages from load_html_files fails, just save mofiles ourselves.

cc_licenses/templates/includes/menu-sidebar.html
https://caktus.atlassian.net/browse/CC-53
This pr reduces the padding of the side-menu to be more inline with the wireframes.
=> [CC-53] Make padding more inline with the wireframe

licenses/templates/legalcode_40_page.html
This PR updates the `legalcode_40` template to display the date when the translation was last updated. This part was originally hard coded while we focused on page styling. Currently no legalcode instance has a populated `datetime` field for `legalcode.translation_last_update`. However this should not be the case once cc31 is merged into develop which deals with pulling translations from transifex.
=> [CC-54] Render date when legal code translation has been last updated

cc_licenses/templates/includes/related_links.html
https://caktus.atlassian.net/browse/CC-56
This ticket is still in blocked. We are waiting on the tooltip component from the vocabulary team. This PR populates the href attributed for the related links section elements.
=> [CC-56] Populate href for related links section.

cc_licenses/templates/includes/deed_body.html, cc_licenses/templates/includes/snippet/icon.html, cc_licenses/templates/includes/snippet/icon_header_snippet.html, licenses/templates/deed_40.html, licenses/tests/test_views.py, licenses/views.py
In 4.0 deeds, display the appropriate icons, rights, and restrictions
depending on which license we're displaying the deed for.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
=> [CCK-22] Display license-appropriate content in deeds

licenses/tests/test_transifex.py, licenses/transifex.py
When a translation has been updated in Transifex and the update checking task has had time to run, the corresponding translation branch in GitHub should have, in its build directory, updated html files corresponding to the updated translation
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> [CC-60] When translation branch has been updated, update its static files in git

cc_licenses/templates/includes/menu-sidebar.html
Update text in sidebar for CC0 to match English messages for translation. They were missing a leading number and a trailing period and so weren't finding their translations.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me and …
```
=> Update text in sidebar for CC0 to match English messages for translation

licenses/models.py, licenses/tests/test_models.py
3.0 license pages weren't displaying the icons to indicate the license properties,
like "non-commercial".
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix logos for non-4.0, non-CC0 licenses

cc_licenses/templates/base.html
V2020.11.2 changed something that made our header links white on white and unreadable.
Header links were white on white and invisible.
Pin vocabulary version to v2020.11.1.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Pin vocabulary version to v2020.11.1.

cc_licenses/templates/base.html
Fix path to vocabulary assets
Had ```@<version>``` in a place where the js was going to add another ```@<version>```.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> Fix path to vocabulary assets

licenses/tests/test_views.py, licenses/urls.py, licenses/views.py, requirements/dev.txt
Fixes #72  by @aldenstpage 
Adds a URL for serving plain text licenses for ported translated licenses, like the French 3.0 BY switzerland license.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
=> Some plaintext legalcode (for ported licenses) not working

README.md, cc_licenses/settings/base.py, docs/dev/provisioning.rst, docs/dev/translation.rst, licenses/management/commands/check_for_translation_updates.py, licenses/tests/test_git_utils.py, licenses/tests/test_utils.py, licenses/utils.py
- Update to reflect `main` is now configured as *default branch* (here and in cc-licenses-data)
- `licenses/tests/test_git_utils.py`
- Also update variable names and comments to increase clarity
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole …
```
=> Update code, settings, and docs for main default branch

licenses/management/commands/publish.py
- Add --nogit to publish command (ex. `pipenv run ./manage.py publish --nogit`). This makes it easier to iterate on template changes, etc.
- Use `self.stdout.write()` instead of `print()` per [Writing custom django-admin commands | Django documentation | Django](https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/)
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
=> add --nogit to publish command

README.md, cc_licenses/settings/local.example.py, cc_licenses/templates/base.html, cc_licenses/templates/includes/deed_40_body.html, cc_licenses/templates/includes/licenses_header.html, cc_licenses/templates/includes/snippet/icon.html, cc_licenses/templates/includes/snippet/icon_header_snippet.html, licenses/git_utils.py, licenses/tests/test_git_utils.py, manage.py, ssh_wrapper.sh
Various quality of life updates for issues I encountered while configuring local dev to publish:
- improve error and exception handling
- improve `TRANSLATION_REPOSITORY_DEPLOY_KEY` related documentation
- increase git_utils test coverage
- reduce HTML template whitespace to reduce delta from previous publish
- update SSH wrapper
- add test for PROJECT_ROOT environment variable
- simply environment variable present verification
- remove unnecessary exec
- improve ssh options
- document testing command line
(For most recent publish, see [Updated built HTML files · creativecommons/cc-licenses-data@04ead6f](https://github.com/creativecommons/cc-licenses-data/commit/04ead6fd9a0cb88191b8ea984724d09d970440ff))
index.md`). …
=> Various clean-ups and clarifications

README.md, cc_licenses/settings/base.py, licenses/management/commands/publish.py, licenses/models.py, licenses/tests/test_models.py, licenses/tests/test_templatetags.py, licenses/tests/test_utils.py, licenses/utils.py
Update publish layout
- Refactor output organization to better match production URLs (also adds symlinks). This will not only make hosting easier, but will also make the data repository useful without special hosting (ex. it could be served via GitHub pages)
- slightly increased test coverage
Symlinks are noted with `^`. Note that unported (`xu` jurisdiction) have symlinks in the parent (ex. `docs/licenses/by-nc-nd/3.0/index.html`):
```
cc-licenses-data/docs
licenses/by-nc-nd/3.0/xu/deed.en
^deed.en
^deed
^index.html
licenses/by-nc-nd/3.0/xu/legalcode.en
^legalcode.en
^legalcode
licenses/by-nc-nd/3.0/am/deed.hy
^deed
^index.html
licenses/by-nc-nd/3.0/am/legalcode.hy
^legalcode
licenses/by-nc-nd/3.0/at/deed.de
^deed
^index.html
licenses/by-nc-nd/3.0/at/legalcode.de
^legalcode …
```
=> Update publish layout

.pre-commit-config.yaml, Pipfile.lock, licenses/git_utils.py, licenses/tests/test_git_utils.py, licenses/tests/test_models.py, licenses/tests/test_transifex.py, licenses/tests/test_views.py, pyproject.toml
- Reduce test noise
- Increase test coverage (added 7 tests)
- Move coverage configuration from command line to configuration file
- Update python dependencies
Old coverage test output:
```
Using existing test database for alias 'default'...
System check identified no issues (0 silenced).
............On branch otherbranch
nothing to commit, working tree clean
...git: 'TestInvalidCommand' is not a git command. See 'git --help'.
......................................................................................................
Ran 117 tests in 3.491s
OK
Preserving test database for alias 'default'...
```
Old coverage report output:
``` …
```
=> Moar coverage

README.md, licenses/management/commands/load_html_files.py
- `load_html_files` Django admin command
- add default `input_directory`
- add an error if the `input_directory` is not a directory
- print source directory and each file as it is loaded
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in …
```
=> add default input_directory to load_html_files Django admin command

licenses/management/commands/publish.py, licenses/models.py, licenses/tests/test_models.py
Remove "xu" and supporting symlinks from unported publish path.
The first update I made to publishing paths had jurisdictions for all 3.0 and earlier licenses ("xu" is a "user assigned code" meaning "unported"). This PR brings the published paths in line with current production paths. While conceptually, treating all 3.0 and earlier licenses the same (having a jurisdiction code), the code is actually simpler without the "xu" jurisdiction since the data model includes jurisdiction (with None values) and the publishing path should not have "xu".
Also see [User-assigned code elements - ISO 3166-1 alpha-2 - Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements).
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900a …
=> remove "xu" and supporting symlinks from unported publish path

licenses/tests/test_views.py, licenses/views.py
Fixes #138
- `licenses/views.py`:
1. Fix issues
- add `status=404` to output of `view_page_not_found` function
- correct default category (`licenses` instead of ~~`license`~~)
- disable plaintext logic in `view_license` function
- `licenses/tests/test_views.py`:
1. Fix issues
- update class and function names to match previous `licenses/views.py` function renames
2. complete text coverage (`licenses/views.py` is now one of the fifteen files skipped):
```
i18n/utils.py              72      1      8      1    97.50%   126
licenses/git_utils.py      83      0     36      3    97.48%   70->exit, 124->126, 140->145
licenses/models.py        241      0 …
```
=> Improve views tests

i18n/tests/test_utils.py
Fixes #140
Complete text coverage (`i18n/utils.py` is now one of the sixteen files skipped):
```
licenses/git_utils.py      83      0     36      3    97.48%   70->exit, 124->126, 140->145
licenses/models.py        241      0     50      1    99.66%   534->542
licenses/transifex.py     201      0     42      1    99.59%   285->293
licenses/utils.py         172      3     78      2    98.00%   60, 154-155
TOTAL                    1000      3    282      7    99.22%
16 files skipped due to complete coverage.
```
index.md`). …
=> Improve i18n test coverage

cc_licenses/templates/includes/deed_unimplemented.html, cc_licenses/templates/includes/deprecated.html, cc_licenses/templates/includes/menu-sidebar.html, licenses/templates/deed.html, licenses/templates/legalcode_page.html, licenses/tests/test_views.py
- Add retired legal tool notice
- unlike the current/legacy ccEngine, the notice is displayed above *both* the deed and the legalcode
- Improve display (and logic) for crude HTML legalcode (legalcode that is loaded simply instead of being fully imported)
- An essentially empty menu (it had only the title) is no longer displayed for cude HTML legalcode 
- [Templates | Django documentation | Django](https://docs.djangoproject.com/en/2.2/ref/templates/)
index.md`).
<details>
```
Version 1.1
Suite D4700
San Francisco, CA, …
```
=> Retired notice

licenses/admin.py, licenses/models.py, licenses/templates/legalcode.html, licenses/tests/test_models.py, licenses/tests/test_views.py, licenses/urls.py, licenses/views.py
disable plaintext functionality
- completely disable plain text file generation (functionality was previously partially disabled)
- ensure the same comment is used throughout for easier discovery/navigation
I disabled the plaintext functionality because it is non-deterministic. The `legalcode.txt` files must not change due to tool chain (ex. pandoc) updates. The plaintext files are sometimes programmatically matched to determine repository licensing.
I did not remove the code, as I expect it may have utility in the future.
```
licenses/git_utils.py      83      0     36      3    97.48%   70->exit, 124->126, 140->145
licenses/models.py        246 …
```
=> Disable plaintext generation

.github/workflows/pre-commit.yml, cc_licenses/settings/base.py, i18n/__init__.py, i18n/utils.py, licenses/apps.py, licenses/templates/dev/home.html, licenses/tests/test_views.py, licenses/views.py
Fixes [[Bug] Deed/UX translations and Legalcode translations must be distinct and fully represented · Issue #146](https://github.com/creativecommons/cc-licenses/issues/146) 
Improve translation handling
- also checkout  [`cc-licenses-data`](https://github.com/creativecommons/cc-licenses-data) and set `DATA_REPOSITORY_DIR` environment variable 
- Add Aragonese to Django languages
- Remove Language fallbacks that are unnecessary with `i18n.utils.cc_to_django_language_code()` update
-  use UTC for time zone
- Correct case in `DEFAULT_JURISDICTION_LANGUAGES` entries
- Remove `DJANGO_LANGUAGE_CODES` entries that are no longer needed  with `i18n.utils.cc_to_django_language_code()` was update
- Improve `cc_to_django_language_code()` to solve generic cases (ex.`_` => `-`).
- added PO file …
=> Language update

i18n/__init__.py, i18n/utils.py, licenses/management/commands/load_html_files.py, licenses/models.py, licenses/templates/dev/home.html, licenses/tests/test_models.py, licenses/tests/test_views.py, licenses/views.py
Improve data representation within metadata.yaml
- improve crude html title clean-up
- add `get_jurisdiction_name()` function
- Add metadata.yaml download to Dev Home page template
- Update data contained within metadata.yaml
- organize by category
- include missing fields
- better represent legal code translations
- Complete test coverage for views
- Reorganize and rename view tests to reflect views code
```yaml
licenses:
- by_40:
canonical_url: https://creativecommons.org/licenses/by/4.0/
deed_only: false
identifier: CC BY 4.0
jurisdiction_name: International
legal_code_languages:
ar: Arabic
cs: Czech
zh-Hans: Simplified Chinese
zh-Hant: Traditional Chinese
permits_derivative_works: true
permits_distribution: true
permits_reproduction: true
permits_sharing: true …
```
=> Improve metadata.yaml

licenses/tests/test_transifex.py, licenses/transifex.py
- Improve transifex test coverage from 64.03% to 100%
- (total test coverage from 91.25% to 99.67%)
- Minor corections to `licenses/transifex.py`:
- improve consistency of argument order
- store date as string instead of object (for easier testing)
- simplify and correct logic within `normalize_pofile_project_id()`
- [Coverage.py][coveragepy]: Code coverage measurement for Python
- [unittest — Unit testing framework — Python 3.7.11 documentation](https://docs.python.org/3.7/library/unittest.html)
- [unittest.mock — mock object library — Python 3.7.11 documentation](https://docs.python.org/3.7/library/unittest.mock.html)
- [Testing in Django | Django documentation | Django](https://docs.djangoproject.com/en/3.2/topics/testing/)
[coveragepy]: https://github.com/nedbat/coveragepy
```
Name …
```
=> Improve transifex test coverage

i18n/__init__.py, i18n/tests/test_utils.py
Fixes #165
- #165
switch language code to `oc-aranes` now that it is supported by Transifex (Code)
- See [Language Codes - README](https://github.com/creativecommons/cc-licenses#language-codes).
- Data PR: [switch language code to oc-aranes (Data) by TimidRobot · Pull Request #30 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/30)
```
TOTAL                    1240      2    364      3    99.69% …
```
=> switch language code to oc-aranes (Code)

.gitignore, cc_licenses/settings/base.py, i18n/tests/test_utils.py, i18n/utils.py, licenses/apps.py, licenses/management/commands/load_html_files.py, licenses/models.py, licenses/templates/dev/translation_status.html, licenses/tests/test_transifex.py, licenses/transifex.py, licenses/views.py
Fixes #182
- #182 
Use locale name for translation directories and add metadata (code)
- Use locale_name instead of language_code for Gettext Files directories
- Add Language-Django and Language-Transifex metadata to Gettext Files (`.po` files)
- Show locale_name in translation stats and improve table layout/display
- Improve PO File data handling / reduce duplication
Corresponding data PR: [Use locale name for translation directories and add metadata (data) by TimidRobot · Pull Request #32 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/32)
```
licenses/git_utils.py      83      2     36      3    95.80% …
```
=> Use locale name for translation directories and add metadata (code)

licenses/management/commands/normalize_translations.py, licenses/management/commands/pull_translation.py, licenses/tests/test_transifex.py, licenses/transifex.py
Improve Transifex integration with "safesync" and "pull"
- Add "safesync" to `normalize_translations` management command--if an entry is empty locally, but a translation exists on Transifex, use it
- Add `pull_translation` management command--overwrite local data with Transifex data
- Improve command line option support of translation domains
see related data PR: [Transifex sync and pull (data) by TimidRobot · Pull Request #41 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/41)
``` …
```
=> Transifex sync and pull (code)

dev/updatemessages.sh
avoid unnecessary churn from `./dev/updatemessages.sh`
- reformat PO Files using polib for consistency
- revert creation date
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> avoid unnecessary churn from ./dev/updatemessages.sh

legal_tools/management/commands/publish.py, legal_tools/models.py, legal_tools/tests/test_models.py
Fixes #213 
- #213
redirect deed-only legalcode (app)
- replace documents containing warnings with redirects for deed-only legalcode
- improve `get_publish_files` tests so they there are multiple tests that
test one thing instead of huge tests with abstraction
also see data PR: [redirect deed-only legalcode (data) by TimidRobot · Pull Request #57 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/57)
```
TOTAL    1329      0    464      0   100.00%
```
index.md`). …
=> redirect deed-only legalcode (app)

i18n/__init__.py, i18n/management/commands/transstats.py, i18n/tests/test_utils.py, i18n/utils.py, legal_tools/management/commands/publish.py
Fixes #177 
- #177 
- Move generation of translation statistics CSV to `i18n.utils` and include in `publish` command
- Remove unused and commented out code
also see data PR: [improve translation statistics CSV (data) by TimidRobot · Pull Request #58 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/58)
```
TOTAL    1347      0    492      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or …
=> improve translation statistics CSV (app)

legal_tools/management/commands/publish.py, legal_tools/utils.py
Complete `xu` removal (app):
- remove special handling of legacy RDF with `xu` jurisdiction 
- improve `save_bytes_to_file()`
- do not use reserved word for variable name
- write with truncation
see related data PR: [Complete xu removal (data) by TimidRobot · Pull Request #62 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/62)
- `xu` was a "user assigned code" meaning "unported"
- [User-assigned code elements - ISO 3166-1 alpha-2 - Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements)
- 2020-09-12 (merged 2020-09-12): support for paths containing `xu` was added in [Move static files by dpoirier · Pull Request #68 · creativecommons/cc-legal-tools-app](https://github.com/creativecommons/cc-legal-tools-app/p …
=> Complete xu removal (app)

templates/base.html, templates/deed.html, templates/legalcode.html
HTML metadata clean-up (app)
- add meta CC-Canonical-URL to Deeds & Legal Code
- add body about to Deeds
- add link rel canonical to Deeds
- correct body typeof spelling
- remove meta Content-Type
- redundant with meta charset
- innaccurate: pages are HTML5
- remove unused meta author
- remove unused meta description
- remove unused meta keywords
- remove unused meta viewport
also see related data PR: [HTML metadata clean-up (data) by TimidRobot · Pull Request #68 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/68)
```
TOTAL    1347      0    492      0   100.00%
19 files …
```
=> HTML metadata clean-up (app)

legal_tools/views.py
Fixes #243
- #243 
app: improve language/translation selection in published files
- activate language sooner in views
also see data PR: https://github.com/creativecommons/cc-legal-tools-data/pull/82
- [Translation | Django documentation | Django](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/)
```
TOTAL    1374      0    492      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source …
=> app: improve language/translation selection in published files

templates/includes/legalcode_crude_html.html
app: use `content` class for "crude html" legal code
- mitigates, but does not fix the following issue:
- https://github.com/creativecommons/vocabulary/issues/1037
also see data PR: https://github.com/creativecommons/cc-legal-tools-data/pull/85
- https://github.com/creativecommons/vocabulary/issues/1037
- https://github.com/jgthms/bulma/issues/2553
- [Content | Bulma: Free, open source, and modern CSS framework based on Flexbox](https://bulma.io/documentation/elements/content/)
```
TOTAL    1374      0    492      0   100.00%
```
index.md`). …
=> app: use content class for "crude html" legal code

i18n/tests/test_utils.py, i18n/utils.py, legal_tools/models.py, legal_tools/tests/test_models.py, legal_tools/tests/test_views.py, legal_tools/views.py
Fixes #273 
- #273
App: fix legal code translations
1. Correct coverage tests failing sometimes by correctly setting up test data (legal code translations can not be reliably loaded if the LegalCode's Tool object does not have a unit
2. Correct published legal code with inconsistent Deeds & UX strings by adding logic to language activation:
1. specified language
2. fallback to jurisdiction default language
3. fallback to default language (LANGUAGE_CODE): en English
Also see Data PR: https://github.com/creativecommons/cc-legal-tools-data/pull/92
```
19 files skipped due to complete …
```
=> App: fix legal code translations

dev/concatenatemessages.sh, legal_tools/management/commands/load_html_files.py
App: add disclaimer translations and remove unused translations
- Add disclaimer translations
- Update `load_html_files` management command to extract disclaimer translations from BY 4.0 licenses and write them to a temporary location
- Update `dev/concatenatemessages.sh` to load translations from the temporary location
- Remove unused translations (English strings removed in #277)
Also see related Data translation PR: https://github.com/creativecommons/cc-legal-tools-data/pull/96
Also see related Data published PR: https://github.com/creativecommons/cc-legal-tools-data/pull/97
``` …
```
=> App: add disclaimer translations and remove unused translations

legal_tools/management/commands/load_html_files.py, templates/includes/about_cc.html
App: add bottom disclaimer translations
- Update `load_html_files` management command to extract bottom disclaimer translations from BY 4.0 licenses and write them to a temporary location
- Clean-up text
- Correct template to match text
Also see related Data translation PR: https://github.com/creativecommons/cc-legal-tools-data/pull/98
Also see related Data published PR: https://github.com/creativecommons/cc-legal-tools-data/pull/99
```
```
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4a …
=> App: add bottom disclaimer translations

README.md
- fix `#docker-compose-setup` anchors
- simple fix of a problem I introduced with a previous search & replace:
- #257 
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```
=> fix #docker-compose-setup anchors

legal_tools/management/commands/load_html_files.py
define variable to resolve UnboundLocalError when only a single cc0 legal code is loaded
Command:
```shell
docker compose exec app ./manage.py load_html_files --versions '1.0' --category publicdomain --languages da --pomofiles -v2
```
Resulting error and stack trace:
```
ERROR 2023-04-05 13:15:11,099 management.commands: Unhandled exception:
```
```python
Traceback (most recent call last):
File "/home/cc/cc-legal-tools-app/./manage.py", line 28, in <module>
main()
File "/home/cc/cc-legal-tools-app/./manage.py", line 23, in main
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line …
```
=> define variable to resolve UnboundLocalError

docker-compose.yml
Fixes #341  by @0saurabh0
Before the change, the development server ran on `0.0.0.0:8005` instead of `127.0.0.1:8005`, as listed by the `README.md`. After a simple configuration change for `docker-compose.yml`, the problem seems to be fixed. (As visible from the screenshot.)
Since the fix was a simple change in the configuration file, the black/isort tests for Python are not necessary. Please note that I've still run all pre-commit hooks beforehand.
index.md`).
<details>
<summary>Developer …
=> [#341] [Fix] Run development server on correct IP address

legal_tools/rdf_generator.py, legal_tools/views.py
- Set RDF.type and pretty print xml for syntactic compression
- Removing the `.replace()` will make future efforts (like sorting) easier
- Based on [Answer 32203700 - python - How to change `rdf:description` namespace using rdflib? - Stack Overflow](https://stackoverflow.com/a/32203700)
👉🏻 @0saurabh0 please merge (into your `rdf_gen` branch), if you do not have any concerns
- [Adding Triples to a graph — Creating RDF triples — rdflib 6.3.2 documentation](https://rdflib.readthedocs.io/en/stable/intro_to_creating_rdf.html#adding-triples-to-a-graph)
> For some properties, only one value per resource makes sense (i.e they are _functional properties_, or have a max-cardinality of 1). The [`set()`](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Graph.set) method is …
=> set RDF.type and pretty print xml for syntactic compression

Pipfile, legal_tools/rdf_generator.py, legal_tools/views.py
add (ugly) support for deterministic RDF/XML generation
It's an ugly solution 🙈 Maybe, in the future, we can instead write an Ordered XML Serializer for rdflib, like was done for Turtle ([scriptotek/otsrdflib](https://github.com/scriptotek/otsrdflib): *Ordered Turtle Serializer for rdflib*).
👉🏻 @0saurabh0 please merge, if you do not have any concerns
1. `rdflib` does not support deterministic output at all
2. `lxml` elements can be ordered, but it does not support deterministic output of the namespace
3. `xml.etree.ElementTree` automatically orders the namespce, but does not support mapping prefixes (this means that the elements can be sorted, but they might appear unsorted in the output)
- [rdflib 6.3.2 — rdflib 6.3.2 documentation](https://rdflib.readthedocs.io/en/stable/index.html#)
- …
=> add support for deterministic RDF/XML generation

templates/base.html, templates/legalcode.html
App: Add temporary attention section to 4.0 by-nc-nd and by-nd until errors are resolved
Also see related Data PR: creativecommons/cc-legal-tools-data#144
Related issues:
- #365
- #366,
- #367
```
```
index.md`).
<details>
``` …
```
=> App: Add temporary attention section to 4.0 by-nc-nd and by-nd

legal_tools/management/commands/publish.py
App: correct language redirects
- creativecommons/cc-legal-tools-data#145
```
```
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> App: correct language redirects

legal_tools/management/commands/load_html_files.py, templates/includes/legalcode_licenses_4.0.html
Fixes #367 
- #367 
App: Fix 4.0 s2a1B logic
- Fix template logic for `by-nc-nd`, `by-nc-sa`, and `by-nd` for Section 2a1B
- `load_html_files.py`: add section header comments and whitespace to improve code navigation
- creativecommons/cc-legal-tools-data#151
```
```
index.md`). …
=> App: Fix 4.0 s2a1B logic

i18n/__init__.py, legal_tools/tests/test_models.py
Fixes #385 
- #385 
App: add en-gb redirect
Also see Data PR:
- creativecommons/cc-legal-tools-data#158
```
```
Testing using [creativecommons/index-dev-env](https://github.com/creativecommons/index-dev-env):
Old:
```
http -h http://localhost:8080/licenses/by-sa/2.0/deed.en-gb
```
```
HTTP/1.1 404 Not Found
Connection: Keep-Alive
Content-Length: 273
Content-Type: text/html; charset=iso-8859-1
Date: Tue, 07 Nov 2023 17:49:30 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.56 (Debian)
```
New:
```
http -h http://localhost:8080/licenses/by-sa/2.0/deed.en-gb
```
```
HTTP/1.1 301 Moved …
```
=> App: add en-gb redirect

README.md, cc_legal_tools/static/cc-legal-tools/base.css, cc_legal_tools/static/cc-legal-tools/deed.css, cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css, legal_tools/tests/test_views.py, legal_tools/urls.py, legal_tools/views.py, templates/base.html, templates/deed.html, templates/legalcode.html
Fixes #361, fixes #390 
- #361 
- #390 
App:
- add tool meta information (canonical url, rdf/xml, plaintext)
- improve consistency of title header
Also see Data PRs:
- creativecommons/cc-legal-tools-data#162
- creativecommons/cc-legal-tools-data#163 (includes screenshots)
- [Box alignment in flexbox - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_box_alignment/Box_alignment_in_flexbox)
- [Mastering wrapping of flex items - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Mastering_wrapping_of_flex_items)
```
TOTAL    1659      0    566      0  100.00%
20 files skipped due to complete …
```
=> App: add tool meta information (canonical url, rdf/xml, plaintext)

templates/includes/legalcode_licenses_4.0.html
App: fix CC BY-NC-ND 4.0 and CC BY-ND 4.0 section 3a1
- Fix template logic
- creativecommons/cc-legal-tools-data#166
```
TOTAL    1659      0    566      0  100.00%
```
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> App: fix CC BY-NC-ND 4.0 and CC BY-ND 4.0 section 3a1

templates/deed.html
App: fix logic for footnote-technological-measures and correctly order footnote-mediation-and-arbitration
- (footnote-mediation-and-arbitration is only visible on CC 3.0 IGO licenses' deeds)
- Follows up on: #400
- creativecommons/cc-legal-tools-data#170
```
```
index.md`).
<details> …
=> App: fix logic for footnote-technological-measures and correctly order footnote-mediation-and-arbitration

cc_legal_tools/static/cc-legal-tools/base.css, templates/base.html
App: improve compatibility with older browsers with better import of Vocabulary Theme CSS
Exacerbates:
- creativecommons/vocabulary-theme#59
- creativecommons/cc-legal-tools-data#181
```
```
index.md`).
<details>
```
Developer …
```
=> App: improve import of Vocabulary Theme CSS

legal_tools/management/commands/publish.py
- Fixes #438
App: Add RedirectMatch for ccEngine bug URLs including bare directory
- creativecommons/cc-legal-tools-data#192
command:
```shell
```
```
TOTAL    1682      0    636      0  100.00%
```
index.md`).
<details>
```
Developer …
```
=> App: Add RedirectMatch for ccEngine bug URLs including bare directory

i18n/tests/test_utils.py, i18n/utils.py, legal_tools/models.py, legal_tools/tests/test_models.py, legal_tools/tests/test_utils.py, legal_tools/tests/test_views.py, legal_tools/utils.py, legal_tools/views.py
- Fixes #444 by @dhruvkb
App: Fix missing canonical URLs
- improve default language logic
- rename ~~`get_default_language_for_jurisdiction`~~ to `get_default_language_for_jurisdiction_naive`
- primarily used for legal code
- add `get_default_language_for_jurisdiction_deed`
- consults `settings.LANGUAGES_MOSTLY_TRANSLATED`
- coincidentally improves `hreflang="x-default"` behavior for ported deeds
- see also: #268 
- creativecommons/cc-legal-tools-data#193
command
```shell
./dev/coverage
```
```
```
index.md`). …
=> App: Fix missing canonical URLs

.gitignore, README.md, dev/stats.sh
Add About section to README and stats script
- Rendered README:
- old/current [`README.md`](https://github.com/creativecommons/cc-legal-tools-app/blob/c0bef3620397acd7cd5693e36d1c60096c4dc27d/README.md)
- new/PR [`README.md`](https://github.com/creativecommons/cc-legal-tools-app/blob/ef26cfe3f85802c5333a7c91d9ba9849ecd2064c/README.md)
- [boyter/scc](https://github.com/boyter/scc): Sloc, Cloc and Code: scc is a very fast accurate code counter with complexity calculations and COCOMO estimates written in pure Go
N/A - no changes to Django app
<details>
<summary>plaintext output</summary>
```
Source code                                                            10:39:37 
DIR_REPO: /Users/timidrobot/git/creativecommons/cc-legal-tools-app …
```
=> Add About section to README and stats script

dev/stats.sh
add more information about the licenses across versions to stats
<details>
<summary>plaintext excerpt</summary>
```
Licenses per license version
Version  Count  Licenses
1.0         14  by  by-nc  by-nc-sa  by-nd  by-nd-nc  by-sa  nc  nc-sa  
nc-sampling+  nd  nd-nc  sa  sampling  sampling+  
2.0         12  by  by-nc  by-nc-nd  by-nc-sa  by-nd  by-sa  devnations  nc  
nc-sa  nd  nd-nc  sa  
2.1          6  by  by-nc  by-nc-nd  by-nc-sa  by-nd  by-sa  
2.5          6  by  by-nc  by-nc-nd  by-nc-sa  by-nd  by-sa  
3.0          6  by  by-nc  by-nc-nd  by-nc-sa  by-nd  by-sa  
4.0          6  by  by-nc  by-nc-nd  by-nc-sa  by-nd  by-sa  
Legal tools per license version
Prior to the international 4.0 version, the licenses were adapted to specific
legal jurisdictions ("ported"). This means …
```
=> add more information about the licenses across versions to stats

templates/deed.html, templates/legalcode.html
- Fixes #451 by @TimidRobot
App: ensure canonical URL is always LTR
- creativecommons/cc-legal-tools-data#195
command:
```shell
```
```
```
See related Data PR:
- creativecommons/cc-legal-tools-data#195
index.md`).
<details>
<summary>Developer …
=> App: ensure canonical URL is always LTR

legal_tools/management/commands/publish.py
- Fixes #236 by @TimidRobot 
App: redirects for deeds with absent languages
- generate contextual redirects for deed URLs of languages that would otherwise 404
- creativecommons/cc-legal-tools-data#200
Tested with [creativecommons/index-dev-env](https://github.com/creativecommons/index-dev-env/):
```
HTTP/1.1 301  http://localhost:8080/licenses/by-nc-nd/1.0/deed.INVALID
>>>>>>>> 200  http://localhost:8080/licenses/by-nd-nc/1.0/deed.en
HTTP/1.1 301  http://localhost:8080/licenses/by-nd-nc/1.0/deed.INVALID
>>>>>>>> 200  http://localhost:8080/licenses/by-nd-nc/1.0/deed.en
HTTP/1.1 301  http://localhost:8080/licenses/sampling/1.0/br/deed.apy
>>>>>>>> 200  http://localhost:8080/licenses/sampling/1.0/br/deed.pt-br
HTTP/1.1 301 …
```
=> App: redirects for deeds with absent languages

cc_legal_tools/static/cc-legal-tools/base.css, cc_legal_tools/static/cc-legal-tools/deed.css, dev/stats.sh, templates/includes/snippet/title_with_icons.html
We've received reports that people are confused about the title of the legal tools with the current design.
- For example, for the **Attribution-NonCommercial-NoDerivs 4.0 International** legal tool, users may think the title is:
- **CC BY-NC-ND 4.0 Deed**
- **CC BY-NC-ND 4.0 Legal Code**
Looking at the screenshots, below, it is easy to see how the current design leads to confusion.
Related to:
- creativecommons/index-prototype#66
App: improve clarity of legal tool title
- creativecommons/cc-legal-tools-data#202
Thank you @possumbilities for help with CSS and HTML!
- [Basic concepts of flexbox - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox)
- Properties
- [align-items - CSS: …
=> App: improve clarity of legal tool title

Dockerfile
- better align `Dockerfile` with [Building best practices | Docker Docs](https://docs.docker.com/build/building/best-practices/)
- reduced from 41 layers 32 layers
command:
```shell
```
```
```
index.md`).
<details>
``` …
```
=> better align Dockerfile with building best practices

cc_legal_tools/settings/dev.py
Disable debug toolbar--it interferes with tests and I very rarely use it:
> ?: (debug_toolbar.E001) The Django Debug Toolbar can't be used with tests
>        HINT: Django changes the DEBUG setting to False when running tests. By default the Django Debug Toolbar is installed because DEBUG is set to True. For most cases, you need to avoid installing the toolbar when running tests. If you feel this check is in error, you can set `DEBUG_TOOLBAR_CONFIG['IS_RUNNING_TESTS'] = False` to bypass this check.
command:
```shell
```
```
```
~~I also verified that publishing …
=> disable debug toolbar

templates/base.html, templates/deed.html, templates/legalcode.html
App: improve clarity and consistency of HTML head titles
- use dash (`-`) as a deliminator  to match the rest of CreativeCommons.org instead of ~~pipe (`|`)~~
- dashes provide a better experience for people using a screen reader
- drop tool identifier (ex. CC BY-NC-SA 4.0) as it is redundant and no longer matches the layout of the title on the page
Also see related Data pull request:
- creativecommons/cc-legal-tools-data#216
Additional discussion on title delimiters:
- creativecommons/tech-support#1093 (private repo)
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license …
=> App: improve clarity and consistency of HTML head titles

.gitignore, cc_legal_tools/settings/base.py, cc_legal_tools/settings/dev.py, cc_legal_tools/urls.py, dev/coverage.sh, dev/stats.sh, i18n/__init__.py, legal_tools/tests/test_views.py, legal_tools/views.py, manage.py, templates/includes/legalcode_contextual_menu.html, templates/includes/legalcode_licenses_4.0.html, templates/includes/legalcode_zero.html
- Fixes #439
App: improve title translation, add caching, enable debug toolbar
- standardize title generation to a single function so that titles are consistent throughout each document
- prioritize legal code translation domain over Deeds & UX translation domain
- add caching so additional overhead only causes a ~30 seconds of additional processing time on a full publish, instead of an additional ~6 minutes
- (additional overhead is most significantly caused by older tools loading a legal code translation domain so they can recommend using the newer tool by title.)
- update title formula per previous pull request:
- #465
- (this update is also necessary to support new translation workflow with Transifex as the source of legal code translations instead of legacy HTML files)
- remove …
=> App: improve title translation, add caching, enable debug toolbar

README.md
- Fixes #467 by @briandominick 
Rearranges the README doc so more technical/tooling/dev-related sections are toward the end, while content intended for "end users" is prioritized after setup instructions.
Also changed a few section headings and transformed sentence-case outliers to title case.
index.md`).
<details>
```
Version 1.1 …
```
=> Reorganize README for usefulness by user roles

README.md
Reference [Foundational technologies](https://opensource.creativecommons.org/contributing-code/foundational-tech/) page instead of having duplicated project documentation
- Old/current [`README.md`](https://github.com/creativecommons/cc-legal-tools-app/blob/89a1a017cc15ece321174fda6f6c171eea352cc0/README.md)
- New/pull request [`README.md`](https://github.com/creativecommons/cc-legal-tools-app/blob/9892ebb88c8702962dc699e975091bb820cac797/README.md)
index.md`).
<details>
<summary>Developer …
=> Reference Foundational Technologies page instead of having duplicated project documentation

cc_legal_tools/static/cc-legal-tools/base.css
- Related to #281 by @TimidRobot 
This pull request hides the site and in-page navigation from pages in `licenses/` and `publicdomain/` when printed. I've tested my changes in Firefox, Chrome, Opera, and Microsoft Edge. 
I added a media query to hide the sitewide header and footer elements when printed to `base.css`. 
To verify:
1. Compile the static site
2. Navigate to http://127.0.0.1:8006/licenses/list.en and go to any of the legal code or deed pages
3. Open the print dialog
4. Confirm the site wide header and footer, as well as the in page navigation (if originally present) are gone.
Site Header
Site Footer
In page navigation
No site header
No site footer
No side navigation
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f5 …
=> Removed site navigation from licenses/ and publicdomain/ on print

i18n/management/commands/nofuzzy_makemessages.py
update nofuzzy override for Django 4.2
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> update nofuzzy override for Django 4.2

cc_legal_tools/static/cc-legal-tools/base.css, cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css, cc_legal_tools/static/wp-content/themes/vocabulary-theme/vocabulary/css/vocabulary.css, cc_legal_tools/static/wp-content/themes/vocabulary-theme/vocabulary/js/vocabulary.js, templates/includes/header.html, templates/includes/legalcode_contextual_menu.html, templates/list-licenses.html, templates/list-publicdomain.html
- Fixes #507
App: update `vocabulary-theme` to `v1.9.4`, update markup and localized stylings to accommodate changes
* updates all local usage of `vocabulary` to match `v1.9.4` of `vocabulary-theme`
* updates relevant markup to match changes
- creativecommons/cc-legal-tools-data/pull/239
command:
```shell
```
```
TOTAL    1800      0    590      0  100.00%
```
See related Data pull request (PR):
- creativecommons/cc-legal-tools-data/pull/239
index.md`).
For the …
=> App: update `vocabulary-theme` to `v1.9.4`, update markup and localized stylings to accommodate changes

cc_legal_tools/static/wp-content/themes/vocabulary-theme/chooser/css/chooser.css, cc_legal_tools/static/wp-content/themes/vocabulary-theme/chooser/js/chooser.js, cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css, dev/copy_theme.sh
- Fixes #510
App: update standalone dev env `vocabulary-theme` to `v1.11.1`
- Update `dev/copy_theme.sh` to include chooser
- Update standalone dev env `vocabulary-theme` to `v1.11.1`
- creativecommons/cc-legal-tools-data/pull/243
command:
```shell
```
```
TOTAL    1800      0    590      0  100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content …
=> App: update standalone dev env `vocabulary-theme` to `v1.11.1`
