creativecommons/cc-legal-tools-app

.travis.yml, Makefile, README.rst, cc_licenses/settings/deploy.py, docs/dev/provisioning.rst, setup.cfg
Add directions for manually deploying a site using this code.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I …
```
=> How to deploy

cc_licenses/templates/includes/about_cc.html, cc_licenses/templates/includes/about_cc_and_license.html, cc_licenses/templates/includes/disclaimer.html
Fixes #[issue number] by @[issue author]
https://github.com/creativecommons/vocabulary/issues/511
https://github.com/creativecommons/vocabulary/pull/502
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to …
```
=> Use Vocabulary "Light Info" Color as the Background Color for Information Divs

cc_licenses/templates/includes/about_cc.html, cc_licenses/templates/includes/about_cc_and_license.html, cc_licenses/templates/includes/disclaimer.html, cc_licenses/templates/includes/legal_code.html, cc_licenses/templates/includes/licenses_header.html, cc_licenses/templates/includes/skiplink.html, cc_licenses/templates/includes/snippet/icon_header_snippet.html, cc_licenses/templates/includes/use_of_licenses.html
https://caktus.atlassian.net/secure/RapidBoard.jspa?rapidView=148&projectKey=CC&modal=detail&selectedIssue=CC-22
This PR:
- Added `b-header` class to headers across all screens so that title case will be enforced in accordance with Figma mockups. - Updated style of skip to main content button
1. To see changes to headers, navigate to: http://localhost:8000/licenses/license/, http://localhost:8000/licenses/sampling/,
and http://localhost:8000/licenses/deed/. Figma mockups: https://www.figma.com/proto/k2XxlRS0JpII6NXDd3K1zc/Mockup?node-id=395%3A180&scaling=min-zoom
2. To see skip to main content button. Press `tab` key on any screen. 
index.md`).
<details>
<summary>Developer Certificate of …
=> [CC-22] Add 'b-header' class to headers

cc_licenses/templates/includes/deed_body.html, cc_licenses/templates/includes/red_alert.html, cc_licenses/templates/includes/related_links.html, cc_licenses/templates/includes/sampling_deed_body.html
https://caktus.atlassian.net/browse/CC-25
This PR makes minor style updates.
1. `red-alert.html`, center align the 'i' icon and add a bit of padding between icon and text
2. 'Sampling Plus 1.0' should not be all caps on sampling deed
3. Lowercase 'Free' 
4. Change 'too' to 'to' 
5. Add a period after 'To perform, display, and distribute copies...' 
6. Under the related links, 'Support Our Work' should show as 'Support our work'
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> [CC-25] Minor Style Updates to Templates

requirements/dev.txt
This PR adds [cc-link-checker](https://github.com/creativecommons/cc-link-checker/pull/98) to `cc-licenses`'s `requirements/dev.txt` file. After installing by running:
```shell
pip install -r requirements/dev.txt
```
the link checker can be run in your shell as so:
```shell
link_checker
```
index.md`).
<details>
```
Version 1.1
Suite D4700
By …
```
=> [CC-21] Add link_checker package to cc-licenses

cc_licenses/templates/base.html, licenses/templates/licenses/deed_detail.html, licenses/templates/licenses/licenses_detail.html, licenses/templates/licenses/sampling_deed_detail.html
https://caktus.atlassian.net/browse/CC-35
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my …
```
=> [CC-35] See the deed/See the legal code button should be aligned with table

cc_licenses/templates/includes/about_cc.html, cc_licenses/templates/includes/deed_body.html, cc_licenses/templates/includes/legal_code.html, cc_licenses/templates/includes/menu-sidebar.html
ticket with screenshots: https://caktus.atlassian.net/secure/RapidBoard.jspa?rapidView=148&projectKey=CC&modal=detail&selectedIssue=CC-36
wireframes: https://www.figma.com/proto/k2XxlRS0JpII6NXDd3K1zc/Mockup?node-id=395%3A65&scaling=min-zoom
<details>
```
Version 1.1
Suite D4700
(a) The contribution …
```
=> [CC-36] Minor Changes 2

licenses/templates/deed_40.html
This PR fixes a bug where the newsletter div was not showing up on deed_40.html.
https://caktus.atlassian.net/browse/CC-47
index.md`).
- [] I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in whole or in part by me …
```
=> [CC-47] Add Newsletter Div back to Deed Page

licenses/templates/legalcode_40_page.html
Fixes next btn positioning on legalcode page.
=> Fixes Next Btn Positioning on LegalCode Page

cc_licenses/templates/includes/breadcrumbs.html, cc_licenses/templates/includes/locale.html, licenses/templates/licenses/deed_detail.html, licenses/templates/licenses/licenses_detail.html, licenses/templates/licenses/sampling_deed_detail.html, licenses/tests/test_views.py
https://caktus.atlassian.net/browse/CC-44
=> [CC-44] Small Language Changes

licenses/management/commands/publish.py
`TRANSLATION_REPOSITORY_DIRECTORY` should be imported through `django.conf.settings`
=> Fix Settings Import In Publish Management Command

cc_licenses/settings/base.py, licenses/views.py
[CC-50] Fix bad merge conflict resolution to get license translation working again
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> [CC-50] Fix bad merge conflict resolution to get license translation working again

.cc-metadata.yml
Fixes #39 by @dhruvkb
Adds .cc-metadata.yml file to the repository.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Add cc metadata file to the repository

cc_licenses/templates/base.html, licenses/templates/deed_40.html, licenses/templates/legalcode_40_page.html
Please see these QA Notes which address why this ticket was re-opened:
- https://caktus.atlassian.net/browse/CC-57?focusedCommentId=57727
=> [CC-57] Breadcrumb Functionality - Add Links for Home and Licenses

licenses/management/commands/publish.py, licenses/models.py, licenses/tests/test_models.py, licenses/tests/test_utils.py, licenses/tests/test_views.py, licenses/urls.py, licenses/utils.py, licenses/views.py
Add a /metadata/ page with the licenses' metadata in YAML format.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Add metadata export

licenses/tests/test_utils.py, licenses/utils.py
We were using the Django test client to call views and get their response, but outside of a developer environment we ran into problems like ALLOWED_HOSTS. Re-write to resolve the URL to its view function and call it directly.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> The way we were getting the output of views failed in real use. Try another approach.

licenses/management/commands/load_html_files.py, licenses/management/commands/publish.py, licenses/models.py, licenses/tests/test_models.py, licenses/tests/test_utils.py, licenses/utils.py
Move static files output to locations requested by @TimidRobot 
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> Move static files

i18n/__init__.py, licenses/management/commands/publish.py
Remove errant / in output path for status page; treat zh as zh-hans
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> Remove errant / in output path for status page; treat zh as zh-hans

README.rst
Starting to work through in the README what the steps are for the various use cases of translation. Treat this PR as a proposal that is looking for feedback.
@Audiosutras @aldenstpage @TimidRobot 
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> First pass at documenting the translation workflow in README

cc_licenses/settings/deploy.py
allow localhost
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best
of my …
```
=> allow localhost

manage.py
Fixes #85  by @sp35
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work that, to the best …
```
=> Fix DJANGO_SETTINGS_MODULE path

DEPRECATED/requirements/base.txt, DEPRECATED/requirements/dev.txt, Pipfile.lock
update python dependencies
index.md`).
- N/A I added tests for the changes I made (if applicable).
- N/A I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> update python dependencies

DEPRECATED/requirements/base.txt, Pipfile, Pipfile.lock
- update django version match to 2.2.x
- update python dependencies
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> update django version match to 2.2.x and update python dependencies

README.md, licenses/management/commands/import_license_data.py
Update to reflect new legacy data location.
- New/Pull Request [README](https://github.com/creativecommons/cc-licenses/blob/89bdacf7baf2577fe729ed72f1b0a54af3dc6a66/README.md)
- Old/Current [README](https://github.com/creativecommons/cc-licenses/blob/a571a5c9459d8201c447be659df025e0384489bb/README.md)
Also see [Import legacy license data by TimidRobot · Pull Request #14 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/14).
index.md`).
- N/A I added tests for the changes I made (if applicable).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Update to reflect new legacy data location

Dockerfile, README.md, docker-compose.yml
Related to #96 
1. Update app docker configuration to support `docker-compose run web python manage.py publish`
2. Add static container to allow easy preview of generated static files
3. Update documentation for clarity and to fully support use of docker during development
- old/current [README](https://github.com/creativecommons/cc-licenses/blob/00073aeb15d21f7b7a6e3760106107d9664014bd/README.md)
- new/PR [README](https://github.com/creativecommons/cc-licenses/blob/14069b38119cbd795917abe932ef6d5349d6c8b3/README.md)
index.md`).
- `NA` I added or updated tests for the changes I made (if applicable).
<details>
```
Developer Certificate of …
```
=> Extend docker setup

.gitignore, Dockerfile, README.md, docker-compose.yml
Moar docker
- fix & document coverage tests
- rename application docker container to **app** (from web)
index.md`).
<details>
```
Version 1.1
Suite D4700
indicated …
```
=> Moar docker (fix & document coverage tests)

.flake8, .gitignore, cc_licenses/settings/base.py, licenses/management/commands/publish.py, pyproject.toml
Related to [RDF generation · Issue #71](https://github.com/creativecommons/cc-licenses/issues/71)
Copy legacy RDF & plaintext files until they can be generated properly
- Publish command:
```shell
docker-compose run app python manage.py publish --nogit --branch=main
```
- Publish command output example: 
- [publish_output.txt](https://github.com/creativecommons/cc-licenses/files/6443111/publish_output.txt)
- Directory context prefixed with hostname (helps indicate, for instance, that the path is in the docker container)
- Symlinks are marked with a caret (`^`)
index.md`).
<details>
```
Version 1.1 …
```
=> Copy legacy RDF & plaintext files until they can be generated properly

README.md, cc_licenses/settings/base.py, i18n/tests/test_utils.py, i18n/utils.py, licenses/management/commands/publish.py, licenses/models.py, licenses/tests/test_git_utils.py, licenses/tests/test_models.py, licenses/tests/test_transifex.py, licenses/transifex.py, licenses/views.py
Fixes #122
rename `TRANSLATION_REPOSITORY_DIRECTORY` to `DATA_REPOSITORY_DIR`
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> rename TRANSLATION_REPOSITORY_DIRECTORY to DATA_REPOSITORY_DIR

Pipfile, Pipfile.lock, licenses/templatetags/bidi.py
- Fixes #130 
- Fixes #133
1. Update Python Black version
2. Update Python dependencies
- Dependabot strips pipenv marker information
3. Update `licenses/templatetags/bidi.py` with trivial whitespace change by new version of Black
index.md`).
- `N/A` I added or updated tests for the changes I made (if applicable).
- `N/A` I added or updated documentation (if applicable).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Python deps

licenses/templates/dev/home.html, licenses/views.py
improve dev home view
- use identifier for public domain tool headings (instead of unit)
- include "License" after version in level 4 headings
```
licenses/git_utils.py      83      0     36      3    97.48%   70->exit, 124->126, 140->145
licenses/models.py        246      1     52      1    99.33%   609
licenses/transifex.py     201      0     42      1    99.59%   285->293
licenses/utils.py         167      1     78      1    99.18%   59
licenses/views.py         126      2     44      2    97.65%   211, 213
TOTAL                    1011      4    290      8    99.08%
15 files …
```
=> improve dev home view

README.md, docker-compose.yml, i18n/__init__.py, licenses/management/commands/check_for_translation_updates.py, licenses/management/commands/load_html_files.py, licenses/templates/legalcode.html, licenses/transifex.py
Various clean-ups
- `README.md`
- Compare fully rendered: 
- New/PR [README.md](https://github.com/creativecommons/cc-licenses/blob/various-cleanup/README.md)
- Old/main [README.md](https://github.com/creativecommons/cc-licenses/blob/main/README.md)
- add python dependency documentation
- improve translation documentation
- fix various formatting, syntax, and whitespace issues
- `docker-compose.yml`
- Use tmpfs for pg_stat_tmp to resolve [postgresql - DOCKER container with postgres, WARNING: could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted - Stack Overflow](https://stackoverflow.com/questions/66325175/docker-container-with-postgres-warning-could-not-open-statistics-file-pg-stat)
- simply app command
- mount static volume as read-only
- …
=> Various clean-ups

Pipfile, Pipfile.lock, cc_licenses/settings/base.py, licenses/apps.py, licenses/management/commands/check_for_translation_updates.py, licenses/management/commands/clear_license_data.py, licenses/management/commands/load_html_files.py, licenses/management/commands/publish.py, licenses/management/commands/upload_license_messages.py, licenses/tests/test_utils.py, licenses/utils.py, licenses/views.py, manage.py
Add verbosity based logging so that management commands can have variable input based on specified verbosity level
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Add verbosity based logging

licenses/management/commands/publish.py, licenses/tests/test_utils.py, licenses/tests/test_views.py, licenses/utils.py, licenses/views.py
Prettify HTML in views (previously, the views generated a mess and it was only prettified when publish process saved views to disk).
Also made some minor improvements to publishing.
```
TOTAL                    1186      2    346      3    99.67%
```
index.md`).
<details>
```
Developer …
```
=> Prettify HTML in views

Pipfile, Pipfile.lock, licenses/tests/test_utils.py, licenses/utils.py
Fixes #179 
- #179
remove unused functions
I have verified which issues are not using.
index.md`).
=> remove unused function

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, Pipfile, Pipfile.lock, licenses/management/commands/push_translation.py, licenses/tests/test_transifex.py, licenses/transifex.py
Fixes #162 
- #162
- add `push_translation` management command
- improve identifiers in log messages
see related data PR: [Transifex push (data) by TimidRobot · Pull Request #43 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/43)
```
TOTAL                    1315      2    452      3    99.72%
18 files skipped due to complete coverage.
```
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4 …
=> Transifex push (code)

cc_licenses/settings/base.py, dev/concatenatemessages.sh, licenses/management/commands/format_pofile.py
- improve legacy translations import
- remove control characters and clean-up whitespace in legacy  translations
- use polib to save pofiles to reduce misleading changes
- increase translation threshold from 32 to 35 since additional translations were imported
see related data PR: [Translations import (data) by TimidRobot · Pull Request #46 · creativecommons/cc-licenses-data](https://github.com/creativecommons/cc-licenses-data/pull/46)
```
TOTAL                    1315      2    452 …
```
=> Translations import (code)

Pipfile.lock, README.md, dev/concatenatemessages.sh, licenses/git_utils.py, licenses/tests/test_git_utils.py
Fixes #205 
- #205 
Small fixes:
- add docker compose link (#205)
- update python deps
- fix stdout target in `dev/concatenatemessages.sh`
- complete `licenses/git_utils.py` test coverage
```
TOTAL    1307      0    444      0   100.00%
```
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Small Fixes

dev/concatenatemessages.sh, i18n/tests/test_transifex.py, i18n/transifex.py
- Improved translation import from legacy [creativecommons/cc.i18n](https://github.com/creativecommons/cc.i18n)
- Add upload to Transifex to safesync
Related data PRs:
1. [Improved translation import 1 (data) by TimidRobot · Pull Request #54 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/54)
2. [Improved translation import 2 (data) by TimidRobot · Pull Request #55 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/55)
```
TOTAL    1315      0    452      0   100.00%
```
index.md`). …
=> Improved translation import (app)

.cc-metadata.yml
- update CC metadata following rename (#212)
- add project to featured
- [CC Metadata file — GitHub Repo Guidelines — Creative Commons Open Source](https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/#cc-metadata-file)
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> update CC metadata following rename

.github/workflows/pre-commit.yml, Pipfile, Pipfile.lock
Fixes #203
Python updates
- update Python dependencies
- remove pipenv pin
- #203 
- [Django 3.2.10 release notes | Django documentation | Django](https://docs.djangoproject.com/en/3.2/releases/3.2.10/)
- [Release 21.12b0 · psf/black](https://github.com/psf/black/releases/tag/21.12b0)
```
TOTAL    1329      0    486      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent …
=> updated python deps and remove pipenv pin

legal_tools/management/commands/publish.py
Fixes #109
- #109
(management commands are not currently covered by tests)
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```
=> Prohibit publish to main

templates/legalcode.html
fix missing related links text on legal code (app)
- fix missing `with show_legal_code=True`
see related data PR: [fix missing related links text on legal code (data) by TimidRobot · Pull Request #60 · creativecommons/cc-legal-tools-data](https://github.com/creativecommons/cc-legal-tools-data/pull/60)
```
TOTAL    1347      0    492      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source …
=> fix missing related links text on legal code (app)

.github/workflows/pre-commit.yml, docker-compose.yml
Improve Docker and GitHub Workflow
- `.github/workflows/pre-commit.yml`
- update repository names
- simplify env configuration
- use latest posgres
- use current pre-commit/action
- `docker-compose.yml`
- use alpine variants for slimmer images
- add comments
```
TOTAL    1347      0    492      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or …
=> Improve Docker and GitHub Workflow

i18n/templatetags/bidi.py, templates/base.html, templates/includes/about_cc.html, templates/includes/about_cc_and_license.html, templates/includes/deprecated.html, templates/includes/disclaimer_40.html, templates/includes/disclaimer_certification.html, templates/includes/disclaimer_zero.html, templates/includes/languages_dropdown.html, templates/includes/legalcode_licenses_4.0.html, templates/includes/legalcode_menu_sidebar.html, templates/includes/legalcode_zero.html, templates/includes/licenses_header.html, templates/includes/related_links.html, templates/includes/snippet/icon.html, templates/includes/snippet/icon_header_snippet.html, templates/legalcode.html, templates/redirect.html
- improve clarity of bidi tags (`start` and `end` were awfully uninformative and difficult to search for)
- renamed `start` to `bidi_start`
- renamed `end` to `bidi_end`
- remove `{% load bidi %}` where neither `{% bidi_start %}` nor `{% bidi_end %}` are used
- removed from `templates/includes/legalcode_menu_sidebar.html`
- "bidi" is short for "bidirectional"
- [Bidirectional text - Wikipedia](https://en.wikipedia.org/wiki/Bidirectional_text)
- Some of the commands below use `ag` ([ggreer/the_silver_searcher: A code-searching tool similar to ack, but faster](https://github.com/ggreer/the_silver_searcher))
```
find templates/ -type f -exec gsed -e's/{% \(end\|start\) %}/{% bidi_\1 %}/g' -i {} +
```
```
ag -l '{% bidi_(end|start) %}' templates/ | sort > tags
```
```
ag -l 'load.*bidi' …
```
=> improve custom bidi tags

.env, .github/workflows/pre-commit.yml, .gitignore, Dockerfile, README.md, cc_legal_tools/settings/local.example.py, dev/concatenatemessages.sh, dev/coverage.sh, dev/resetdb.sh, dev/tools.sh, dev/updatemessages.sh, docker-compose.yml, docs-outdated/translation.md
app: docker update
- updated to reflect that docker compose is now part of docker
- static docker service
- move config to cc-legal-tools-data so it can also be used by itself (or included here)
- app docker service
- improve Dockerfile documentation and flow control
- use subdirectories for cc-legal-tools-app and cc-legal-tools-data so that operating user data not written to mounted cc-legal-tools-app repository
- github actions
- remove pandoc install
these docker updates must be combined with data PR:  https://github.com/creativecommons/cc-legal-tools-data/pull/86
```
TOTAL    1374      0    492      0   100.00%
19 files …
```
=> app: docker update

README.md, cc_legal_tools/settings/local.example.py, legal_tools/views.py, templates/base.html
App: update frontend component versions
- Update Bulma from ~~`0.9.1`~~ to `0.9.3`
- Update Vue from ~~`3.2.29`~~ to `3.2.31`
- Update cc-global-components from ~~`0.3.0`~~ to `0.4.0`
- Add [Frontend Dependencies](https://github.com/creativecommons/cc-legal-tools-app/blob/bfcd14ecdb0d1b0849e744332ecc540e8c29cb1b/README.md#frontend-dependencies) section to README
- local settings: remove no longer needed `ALLOWED_HOSTS` and disable `XFrameOptionsMiddleware`
- update dev menu to better reflect expected production
Also see related Data PR:  https://github.com/creativecommons/cc-legal-tools-data/pull/88
- [Clickjacking Protection | Django documentation | Django](https://docs.djangoproject.com/en/3.2/ref/clickjacking/)
- [X-Frame-Options - HTTP | …
=> App: update frontend component versions

templates/base.html
App: update frontend component versions v20220304
- Update cc-global-components from ~~`0.4.0`~~ to `0.5.0`
- Update vocabulary-styles from ~~`0.2.1`~~ to `0.3.0`
Also see related Data PR:  https://github.com/creativecommons/cc-legal-tools-data/pull/88
```
TOTAL    1371      0    490      0   100.00%
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public …
=> App: update frontend component versions v20220304

legal_tools/views.py, templates/dev/index.html
Fixes #266 
- #266
App: add Deeds & UX languages counts to dev index
Also see related Data PR: https://github.com/creativecommons/cc-legal-tools-data/pull/91
```
TOTAL    1366      0    468      0   100.00%
```
index.md`).
<details>
```
Developer …
```
=> App: add Deeds & UX languages counts to dev index

Pipfile.lock
update python deps:
| Package | Old Version | ➡️ | New Version |
| --- | :-: | :-: | :-: |
| black | ~~`22.1.0`~~ | ➡️ | `22.3.0` |
| click | ~~`8.0.3`~~ | ➡️ | `8.1.1` |
| coverage | ~~`6.3.1`~~ | ➡️ | `6.3.2` |
| faker | ~~`13.0.0`~~ | ➡️ | `13.3.4` |
| filelock | ~~`3.5.1`~~ | ➡️ | `3.6.0` |
| gitpython | ~~`3.1.26`~~ | ➡️ | `3.1.27` |
| identify | ~~`2.4.10`~~ | ➡️ | `2.4.12` |
| lxml | ~~`4.7.1`~~ | ➡️ | `4.8.0` |
| parsimonious | ~~`0.8.1`~~ | ➡️ | `0.9.0` |
| platformdirs | ~~`2.5.0`~~ | ➡️ | `2.5.1` |
| pytz | ~~`2021.3`~~ | ➡️ | `2022.1` |
| regex | ~~*None*~~ | ➡️ | `2022.3.15` |
| urllib3 | ~~`1.26.8`~~ | ➡️ | `1.26.9` |
| virtualenv | ~~`20.13.1`~~ | ➡️ | `20.14.0` |
``` …
```
=> update python deps

Pipfile.lock, i18n/tests/test_transifex.py
Python and tests updates
- Babel update included changes to language names
See related data PR: https://github.com/creativecommons/cc-legal-tools-data/pull/100
- [NVD - CVE-2022-28347](https://nvd.nist.gov/vuln/detail/CVE-2022-28347)
- [CWE - CWE-89: Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection') (4.7)](https://cwe.mitre.org/data/definitions/89.html)
```
```
index.md`).
For the purposes of this DCO, …
=> Python and tests updates

Pipfile.lock
update python package versions
after rebuilding docker services:
```
docker compose exec app pip list
```
```
Package              Version
-------------------- -----------
asgiref              3.5.2
asttokens            2.0.5
Babel                2.10.3
beautifulsoup4       4.11.1
black                22.3.0
certifi              2022.6.15
cfgv                 3.3.1
charset-normalizer   2.0.12
click                8.1.3
colorlog             6.6.0
coverage             6.4.1
dealer               2.1.0
distlib              0.3.4
Django               3.2.13
django-debug-toolbar 3.5.0
factory-boy          3.2.1
Faker                13.14.0
filelock             3.7.1
flake8               4.0.1
future               0.18.2
gitdb                4.0.9
GitPython            3.1.27
identify …
```
=> update python package versions

.github/workflows/django-app-coverage.yml, .github/workflows/static-analysis.yml, Pipfile, Pipfile.lock
- Update GitHub Actions packages to latest
- ~~actions/checkout@v2~~ => actions/checkout@v3
- [actions/checkout](https://github.com/actions/checkout): Action for checking out a repo
- ~~actions/setup-python@v2~~ => actions/setup-python@v4
- [actions/setup-python](https://github.com/actions/setup-python): Set up your GitHub Actions workflow with a specific version of Python
- Update Python packages to latest
```diff 
--- piplist.old	2022-08-10 08:45:09.000000000 -0700
+++ piplist.new	2022-08-10 08:45:09.000000000 -0700
@@ -1,64 +1,61 @@
Package              Version
asgiref              3.5.2
-asttokens            2.0.5
+asttokens            2.0.7
Babel                2.10.3
beautifulsoup4       4.11.1
black                22.6.0
certifi              2022.6.15
cfgv                 3.3.1 …
```
=> GitHub Actions and Python package updates

README.md, legal_tools/management/commands/load_html_files.py, legal_tools/models.py, legal_tools/tests/test_models.py, templates/includes/legalcode_menu_sidebar.html
use "legal tools", "public domain tools", or "dedication" instead of "~~declaration~~" depending on the scope of the tools referenced
```
```
index.md`).
<details>
``` …
```
=> use more accurate terms instead of "declaration"

README.md
Fixes #292 by @TimidRobot 
Re-arranged README.md file to properly setup on every local workspace without providing bugs during setup
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Re-arrange README.md file

cc_legal_tools/static/cc-legal-tools/base.css, templates/base.html, templates/includes/newsletter.html
The input field to get lasted updates was not well style and misaligned. This PR raised with respect to the issue #264 
index.md`).
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Fix: "Get The Latest Updates" input field and join button are misaligned

README.md
Fixes #300 by @thormiwa
Added a sub step that tells people how to change directory into the cc-legal-tools-app directory before running the copy command
index.md`).
=> Readme.md minor clarity 

Pipfile, Pipfile.lock
Fixes https://github.com/advisories/GHSA-qrw5-5h28-6cmg
- update python modules:
```diff
--- piplist.old	2022-10-19 08:39:01.000000000 -0700
+++ piplist.new	2022-10-19 08:39:01.000000000 -0700
@@ -6 +6 @@
-black                22.8.0
+black                22.10.0
@@ -12 +12 @@
-coverage             6.4.4
+coverage             6.5.0
@@ -15 +15 @@
-Django               3.2.15
+Django               3.2.16
@@ -18 +18 @@
-Faker                15.0.0
+Faker                15.1.1
@@ -23,2 +23,2 @@
-GitPython            3.1.27
-identify             2.5.5
+GitPython            3.1.29
+identify             2.5.6
@@ -33,2 +33,2 @@
-pip                  22.2.2
-pipenv               2022.9.24
+pip                  22.3
+pipenv               2022.10.12
@@ -42 +42 @@
-pytz                 2022.2.1
+pytz …
```
=> update python modules

README.md
Fixes #303  by @TimidRobot 
this pr resolves the issue of windows users not being able to setup docker and pipenv locally
- ~~old/current [`README.md`](https://github.com/creativecommons/cc-legal-tools-app/blob/1906a880c5a822c59c2ff08ce174ec379421475c/README.md)~~
- new/PR [`README.md`](https://github.com/ImaJin14/cc-legal-tools-app/blob/de6e17759355ca6bad239c2163c3a63ae92d0c36/README.md)
index.md`).
<details>
``` …
```
=> Add windows specific notes, update README.md file

cc_legal_tools/static/cc-legal-tools/base.css
Fixes [#52](https://github.com/creativecommons/cc-global-components/issues/52) by @yokwejuste 
This PR is aimed at the realignment of the footer email placeholder.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> fix: aligned email field placeholder

README.md
Fixes #334  by @Lakshay-Pruthi
Fixes typos and Grammatical mistakes in the Readme file.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> Grammatical Mistakes Fixed in Readme

templates/list-publicdomain.html
Fixes #335  by @0saurabh0
Earlier, the placement of the whole public domain list wasn't at its best.
Adjusted the dimensions of "public domain list" table.
**Before**
**After**
**Before**
**After**
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```
=> modified the alignment of 'public domain list'.

README.md
Correct documentation
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
=> correct static file generation description

rdf.md
document RDF/XML namespaces
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> document RDF/XML namespaces

legal_tools/views.py
fix deterministic output for RDF/XML
- replace use of `xml.etree.ElementTree` with simple list and string methods for a more lightweight solution with fewer moving parts
- [Why doesn't the pretty_print option reformat my XML output? - lxml FAQ - Frequently Asked Questions](https://lxml.de/FAQ.html#why-doesn-t-the-pretty-print-option-reformat-my-xml-output)
- this is why there were previously indentation inconsistencies
Previously the differences in output were only visible when Django reloaded.
Process for testing output:
1. Save  output to file:
```shell
http http://localhost:8005/licenses/by/3.0/es/rdf > A
```
2. Reload Django, save new output, and compare:
```shell
touch legal_tools/views.py; sleep 3; http http://localhost:8005/licenses/by/3.0/es/rdf > B; diff -u A B 
```
index.md`). …
=> fix deterministic output for RDF/XML

.github/CODEOWNERS, Pipfile, Pipfile.lock, legal_tools/management/commands/publish.py, legal_tools/rdf_generator.py, legal_tools/urls.py, legal_tools/views.py, rdf.md
This pull request documents the comprehensive contributions made during my Google Summer of Code (GSoC) project for the "CC Legal Tools: Machine-Readable Layer."
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
=> Feature/machine layer changes (GSoC'23)

legal_tools/management/commands/publish.py
App: fix context of lowercase rewrite
See related Data PR:
- creativecommons/cc-legal-tools-data#150
```
```
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> App: fix context of lowercase rewrite

templates/includes/legalcode_licenses_4.0.html
Fixes #366 
- #366 
App: fix legalcode_licenses_4.0.html template s4a logic for `by-nc-nd` and `by-nd`
- creativecommons/cc-legal-tools-data#152
```
```
index.md`).
<details>
```
Version 1.1
Copyright …
```
=> App: fix legalcode_licenses_4.0.html template s4a logic for by-nc-nd and by-nd

legal_tools/management/commands/load_html_files.py, templates/includes/legalcode_licenses_4.0.html, templates/legalcode.html
Fixes #365 
- #365 
App: include 4.0 ND s3a1 trailing sentence and remove temp attention notice
- update legacy HTML import to include trailing sentence
- update template to display sentence
- remove temporary attention notice
Also see related Data PRs:
- creativecommons/cc-legal-tools-data#153
- creativecommons/cc-legal-tools-data#154
```
```
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to …
=> App: include 4.0 ND s3a1 trailing sentence and remove temp attention notice

cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css, templates/base.html
Fixes #386 
- #386 
- update dev vocabulary-theme to 1.3
- add donation banner
Also see Data PR:
- creativecommons/cc-legal-tools-data#157
```
```
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> App: add donation banner

templates/includes/legalcode_licenses_4.0.html
App: fix CC BY-NC-SA 4.0  section 2a1A
Also see Data PR:
- creativecommons/cc-legal-tools-data#164
```
```
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> App: fix CC BY-NC-SA 4.0  section 2a1A

templates/base.html
Fixes #398 
- #398 
App: update end of year fundraising notice banner
See related Data PR:
- creativecommons/cc-legal-tools-data#171
```
```
See related Data PR:
- creativecommons/cc-legal-tools-data#171
index.md`).
<details>
```
Developer Certificate of …
```
=> App: update end of year fundraising notice banner

cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css, templates/base.html
Fixes #404 
- #404 
App: update end of year fundraising notice banner to high-importance
- Update banner text and classes
- Update dev bundled vocabulary-theme to 1.3.2
- creativecommons/cc-legal-tools-data#176
```
```
index.md`).
<details>
<summary>Developer Certificate of …
=> App: update end of year fundraising notice banner to high-importance

Pipfile, Pipfile.lock, cc_legal_tools/settings/base.py, i18n/transifex.py, legal_tools/bs_utils.py, legal_tools/git_utils.py, legal_tools/management/commands/load_html_files.py, legal_tools/models.py, legal_tools/views.py
Fixes:
- 🟡 [Django denial-of-service attack in the intcomma template filter · CVE-2024-24680 · GitHub Advisory Database](https://github.com/advisories/GHSA-xxj9-f6rv-m3x4)
- 🟠 [Untrusted search path under some conditions on Windows allows arbitrary code execution · CVE-2024-22190 · GitHub Advisory Database](https://github.com/advisories/GHSA-2mqj-m65w-jghx)
Update python modules and formatting with new version of Black
```diff
--- piplist.old	2024-02-15 07:59:02
+++ piplist.new	2024-02-15 07:59:02
@@ -4,4 +4,4 @@
-Babel                2.13.1
-beautifulsoup4       4.12.2
-black                23.10.1
-certifi              2023.7.22
+Babel                2.14.0
+beautifulsoup4       4.12.3
+black                24.2.0
+certifi              2024.2.2
@@ -11,2 +11,2 @@
-colorlog …
```
=> Update python modules and formatting with new version of Black

templates/base.html
Fixes #410 
- #410 
App: Remove end of year fundraising notice banner
Also see Data PR:
- creativecommons/cc-legal-tools-data#182
```
```
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and …
```
=> App: Remove end of year fundraising notice banner

.github/workflows/django-app-coverage.yml, .github/workflows/static-analysis.yml
- update to actions/checkout@v4
- https://github.com/actions/checkout/releases
- update to actions/setup-python@v5
- https://github.com/actions/setup-python/releases/tag/v5.0.0
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```
=> update to actions/checkout@v4 and actions/setup-python@v5

.github/workflows/django-app-coverage.yml, .github/workflows/static-analysis.yml, .pre-commit-config.yaml, Dockerfile, Pipfile, Pipfile.lock, README.md, pyproject.toml
- 🟡 [Black vulnerable to Regular Expression Denial of Service (ReDoS) · CVE-2024-21503 · GitHub Advisory Database](https://github.com/advisories/GHSA-fj7x-q9j7-g6q6)
- ⚪ [Regular expression denial-of-service in Django · CVE-2024-27351 · GitHub Advisory Database](https://github.com/advisories/GHSA-vm8q-m57g-pff3)
Update to python 3.10
- This moves the project closer to the eventual goal of Django 4.2 (LTS) and Python 3.11.
```diff
--- piplist.old	2024-04-04 10:12:12
+++ piplist.new	2024-04-04 10:12:12
@@ -2 +2 @@
-asgiref              3.7.2
+asgiref              3.8.1
@@ -6 +6 @@
-black                24.2.0
+black                24.3.0
@@ -12 +12 @@
-coverage             7.4.1
+coverage             7.4.4
@@ -15 +15 @@
-Django               3.2.24
+Django               3.2.25
@@ -18,2 …
```
=> update to python 3.10

docker-compose.yml
Fixes #432 by @TimidRobot
- #432
Use docker compose v2 for non swarm deployments
See linked issue.
```
TOTAL    1662      0    578      0  100.00%
```
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> Use docker compose v2 for non swarm deployments

.github/workflows/django-app-coverage.yml, .github/workflows/static-analysis.yml, .pre-commit-config.yaml, Dockerfile, Pipfile, Pipfile.lock, README.md, legal_tools/urls.py, pyproject.toml
- 😬 Django 3.2 no longer supported
- [Supported Versions | Download Django | Django](https://www.djangoproject.com/download/#supported-versions):
> ### Unsupported previous releases
> These release series no longer receive security updates or bug fixes.
> Release Series | Latest Release | End of mainstream support | End of extended support
> -- | -- | -- | --
> [...] | | |
> 3.2 LTS | 3.2.25 | December 7, 2021 | April 1, 2024
> [...] | | |
- 🟠 [sqlparse parsing heavily nested list leads to Denial of Service · GHSA-2m57-hf25-phgg · GitHub Advisory Database](https://github.com/advisories/GHSA-2m57-hf25-phgg)
- 🟡 [Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode · CVE-2024-3651 · GitHub Advisory …
=> upgrade to Python 3.11 and Django 4.2

README.md, cc_legal_tools/settings/base.py
- update Django documentation URLs to 4.2
- (should have been included in #435)
- no functional changes
- each of the new links resolves as expected
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
=> update Django documentation URLs to 4.2

.github/workflows/check-python-versions.yml, dev/check_python_versions.sh
Add script and workflow to check Python versions
The Python version is tracked in too many files for me to feel confident I'll always remember to update each of them.
it's just a little guy:
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Add script and workflow to check Python versions

Dockerfile, README.md, docker-compose.yml
- Fix Python version in documentation
- should have been included in: #435
- Remove `version:` from `docker-compose.yml`
- docker/compose#11628
- [Version top-level element (obsolete)](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element-obsolete)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Fix Python version in documentation

i18n/tests/test_transifex.py, i18n/transifex.py, legal_tools/git_utils.py, legal_tools/tests/test_git_utils.py
Revisit and fix tests following upgrade to Python 3.11
Embarrassingly, all of the coverage exclusions except one proved to actually be a lack of coverage 😬 
command:
```shell
```
```
TOTAL    1682      0    636      0  100.00%
```
index.md`).
<details>
```
Developer …
```
=> Revisit and fix tests following upgrade to Python 3.11

i18n/__init__.py, legal_tools/management/commands/publish.py, legal_tools/utils.py
Related to:
- #236 
App: add apache only filter and remove lowercase from publish management command
- lowercase was moved to parent config:
- Dev environment: creativecommons/index-dev-env#72
- Stage/Prod environments: creativecommons/sre-salt-prime#284
- update `save_bytes_to_file()` function to use write-only instead of read/write
- (`save_bytes_to_file()` is only used by publish management command and never supported reading)
- creativecommons/cc-legal-tools-data#199
command:
```shell
```
```
```
index.md`). …
=> App: add apache only filter and remove lowercase from publish management command

templates/dev/index.html
App: fix ccREL `schema.rdf` link from dev index page
- creativecommons/cc-legal-tools-data#205
(Django app serves it from `static/` path, published sites does not)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> App: fix ccREL schema.rdf link from dev index page

cc_legal_tools/static/cc-legal-tools/base.css
App: remove errant forward slash (fix typo) in CSS
Also see related Data pull request:
- creativecommons/cc-legal-tools-data#215
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcreativecommons.org%2Flicenses%2Fby%2F4.0%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
index.md`).
<details>
```
Version 1.1
1 Letterman …
```
=> App: remove errant forward slash (fix typo) in CSS

README.md
- Fixes #468 by @briandominick
1. Re-titles several section headings. The strategy here was to better describe what each subsection is about, and to add prereq sections for all OSes.
2. Treat Git as a dependency that some users may not already have and explicitly instruct prereqs for all OSes. Developers are expected to have Git, but translators and others who might need to generate files may not. It's tradition to treat Git as a given on GitHub, but this tends to alienate non-devs. This seemed to be recognized by the link to how to clone a repo, so I just extended it to how to install. Then I added explicit Git commands. This was somewhat against advice in the Issue review by @TimidRobot , but it seemed odd to have step=by-step terminal instructions without providing convenient `git …
=> Docs: Improve setup instructions for less technical users

templates/dev/404.html, templates/legalcode.html
- Fixes #283
App: Remove unused JavaScript
Also see related Data pull request:
- creativecommons/cc-legal-tools-data/pull/221
command:
```shell
```
```
TOTAL    1800      0    690      0  100.00%
```
index.md`).
<details>
```
Version 1.1 …
```
=> App: Remove unused JavaScript

templates/base.html
- Fixes #490 by @possumbilities
App: add 2024 end of year fundraising notice banner
- creativecommons/cc-legal-tools-data/pull/225
command:
```shell
```
```
TOTAL    1800      0    690      0  100.00%
```
index.md`).
<details> …
=> App: add 2024 end of year fundraising notice banner

templates/base.html
- Fixes #492 by @possumbilities
App: update to end of year fundraising banner 2nd phase
- creativecommons/cc-legal-tools-data/pull/226
command:
```shell
```
```
TOTAL    1800      0    690      0  100.00%
```
index.md`).
<details>
<summary>Developer Certificate of …
=> App: update to end of year fundraising banner 2nd phase

templates/base.html
- Fixes #495 by @possumbilities
App: update to end of year fundraising banner phase 3
- creativecommons/cc-legal-tools-data/pull/227
command:
```shell
```
```
TOTAL    1800      0    690      0  100.00%
```
index.md`).
<details> …
=> App: update to end of year fundraising banner phase 3

Pipfile, Pipfile.lock
- 🟠 [Django SQL injection in HasKey(lhs, rhs) on Oracle · CVE-2024-53908 · GitHub Advisory Database](https://github.com/advisories/GHSA-m9g8-fxxm-xg86)
- 🟡 [Django denial-of-service in django.utils.html.strip_tags() · CVE-2024-53907 · GitHub Advisory Database
](https://github.com/advisories/GHSA-8498-2h75-472j)
- Update Python modules (Django 4.2.17, etc.)
- ⚠️ **Requires docker images to be rebuilt (`docker compose build`)**
```shell
git checkout main
docker compose up
docker compose exec app pip list > piplist.old
docker compose down
git checkout -b update-python
pipenv update --dev
docker compose build
docker compose up
docker compose exec app pip list > piplist.new
docker compose down
gsed -e'/^---/d' -i piplist.*
diff -u piplist.old piplist.new
```
```diff
--- piplist.old	2025-01-08 …
```
=> Update Python modules (Django 4.2.17, etc.)

templates/base.html
- Fixes #505 
App: Remove 2024 end of year fundraising banner
- creativecommons/cc-legal-tools-data/pull/238
command:
```shell
```
```
TOTAL    1800      0    590      0  100.00%
```
See related Data pull request (PR):
- creativecommons/cc-legal-tools-data/pull/238
index.md`). …
=> App: Remove 2024 end of year fundraising banner

cc_legal_tools/static/wp-content/themes/vocabulary-theme/style.css
- Related to #510
App: update dev `vocabulary-theme` to `v1.10`
- creativecommons/cc-legal-tools-data/pull/242
command:
```shell
```
```
TOTAL    1800      0    590      0  100.00%
```
index.md`).
<details>
```
Developer …
```
=> App: update dev `vocabulary-theme` to `v1.10`

cc_legal_tools/static/cc-legal-tools/base.css
- Fixes #513 
App: Fix ancillary menu LTR spacing
- creativecommons/cc-legal-tools-data/pull/245
improvement:
no change:
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing …
```
=> App: Fix ancillary menu LTR spacing
